app:
  path_to_rac: "C:/Program Files/1cv8/8.3.14.1857/bin/rac.exe"
  path_to_1cs: "C:/Program Files/1cv8/8.3.14.1857/bin/1cv8.exe"
  lock_code: "12345"

logger:
  level: "debug"  
  path: "log.log"